const db=firebase.firestore();function isMobileDevice(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)}function appendUnwatchedMovieList(a){movieList.innerHTML+=`<li data-movieUnwatched="${a}"> ${a} <select data-movie="${a}" id="ratings">
    <option value="null" selected>Select Rating</option>
    <option value="bad">Bad</option>
    <option value="meh">Meh</option>
    <option value="pretty-good">Pretty Good</option>
    <option value="great">Great</option>
    <option value="masterpiece">Masterpiece</option>
    <option value="remove">Remove Movie</option>
    </select></li>`,generateEventListeners()}function appendWatchedMovieList(a,b){watchedMovies.querySelector(`.${b}-container`).innerHTML+=`<div class="${b} watched-movie" data-movieWatched="${a}" watched-movie"> ${a} <button id="unwatch" data-movie="${a}">Unwatch/Rate</button></div>`,generateEventListeners()}function generateEventListeners(){ratingDropDowns=document.querySelectorAll("#ratings"),ratingDropDowns.forEach(a=>a.addEventListener("change",rate)),unrateButtons=document.querySelectorAll("#unwatch"),unrateButtons.forEach(a=>a.addEventListener("click",unrate))}const useButton=document.querySelector(".login");useButton.addEventListener("click",generate);function generate(){let a=window.prompt();"suhdood"==a&&(generateEventListeners(),addMovieButton.disabled=!1,document.querySelectorAll("button").forEach(a=>a.disabled=!1),ratingDropDowns.forEach(a=>a.disabled=!1))}const randomNumButton=document.querySelector("#random"),randomNumDisplay=document.querySelector(".rand-gen-display");let randomClicks=0;function generateRandom(){const a=movieList.querySelectorAll("li"),b=a.length;0==randomClicks&&(randomNumDisplay.innerHTML=""),randomNumDisplay.innerHTML+=`<div class="random-movie">${a[Math.floor(Math.random()*b)].childNodes[0].textContent}</div>`,randomClicks++,5<randomClicks&&(alert("JUST PICK A FREAKING MOVIE ALREADY"),randomNumButton.disabled=!0,randomNumButton.style.backgroundImage="url(pickone.jpeg)",randomNumButton.style.width="300px",randomNumButton.style.height="168px",randomNumButton.textContent="DISABLED")}randomNumButton.addEventListener("click",generateRandom);const movieList=document.querySelector(".unwatched-movies"),watchedMovies=document.querySelector(".watched-movies");let ratingDropDowns=document.querySelectorAll("#ratings");function generateMovieList(){console.log(isMobileDevice);db.collection("Movies").get().then(function(a){a.forEach(function(a){!0==a.data().watched?watchedMovies.querySelector(`.${a.data().rating}-container`).innerHTML+=`<div class="${a.data().rating} watched-movie" data-movieWatched="${a.data().Title}" watched-movie"> ${a.data().Title} <button id="unwatch" data-movie="${a.data().Title}" disabled=true>Unwatch/Rate</button></div>`:movieList.innerHTML+=`<li data-movieUnwatched="${a.data().Title}"> ${a.data().Title} <select data-movie="${a.data().Title}" id="ratings" disabled=true>
                <option value="null" selected>Select Rating</option>
                <option value="bad">Bad</option>
                <option value="meh">Meh</option>
                <option value="pretty-good">Pretty Good</option>
                <option value="great">Great</option>
                <option value="masterpiece">Masterpiece</option>
                <option value="remove">Remove Movie</option>
                </select></li>`})})}generateMovieList();const addMovieButton=document.querySelector("#add-movie-submit"),addMovieText=document.querySelector("#add-movie");function addMovie(){let a=addMovieText.value;db.collection("Movies").doc(a).set({Title:a}).then(()=>console.log("document written")).catch(()=>console.error("doc writing error")),addMovieText.value="",appendUnwatchedMovieList(a)}addMovieButton.addEventListener("click",addMovie);function rate(){console.log(this.value);const a=this.dataset.movie;"remove"==this.value?db.collection("Movies").doc(a).delete():db.collection("Movies").doc(a).update({watched:!0,rating:`${this.value}`});const b=document.querySelector(`[data-movieUnwatched = "${a}"]`);movieList.removeChild(b),"remove"!=this.value&&appendWatchedMovieList(a,this.value)}function unrate(){console.log("test");const a=this.dataset.movie;db.collection("Movies").doc(a).set({Title:a});const b=watchedMovies.querySelector(`[data-movieWatched="${a}"]`),c=b.classList[0];console.log(b),watchedMovies.querySelector(`.${c}-container`).removeChild(b),appendUnwatchedMovieList(a)}